import "./globals.css";
import { Cabin, DynaPuff, Lexend, Gluten } from "next/font/google";

const cabin = Cabin({ subsets: ["latin"] });
const dyna = DynaPuff({ subsets: ["latin"] });
const lexend = Lexend({ subsets: ["latin"] });
const gluten = Gluten({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gluten.className} text-xl`}>
        <nav>
          <ul className="flex items-center justify-between p-24">
            <li>
              <a href="/">OY Scavenger Hunt</a>
            </li>
            <li>
              <a href="/team/me">My team</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
